// Code generated by mockery v2.36.0. DO NOT EDIT.

package middlewares

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockImiddlewares is an autogenerated mock type for the Imiddlewares type
type MockImiddlewares struct {
	mock.Mock
}

type MockImiddlewares_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImiddlewares) EXPECT() *MockImiddlewares_Expecter {
	return &MockImiddlewares_Expecter{mock: &_m.Mock}
}

// ValidateToken provides a mock function with given fields: next
func (_m *MockImiddlewares) ValidateToken(next echo.HandlerFunc) echo.HandlerFunc {
	ret := _m.Called(next)

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func(echo.HandlerFunc) echo.HandlerFunc); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// MockImiddlewares_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockImiddlewares_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - next echo.HandlerFunc
func (_e *MockImiddlewares_Expecter) ValidateToken(next interface{}) *MockImiddlewares_ValidateToken_Call {
	return &MockImiddlewares_ValidateToken_Call{Call: _e.mock.On("ValidateToken", next)}
}

func (_c *MockImiddlewares_ValidateToken_Call) Run(run func(next echo.HandlerFunc)) *MockImiddlewares_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.HandlerFunc))
	})
	return _c
}

func (_c *MockImiddlewares_ValidateToken_Call) Return(_a0 echo.HandlerFunc) *MockImiddlewares_ValidateToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImiddlewares_ValidateToken_Call) RunAndReturn(run func(echo.HandlerFunc) echo.HandlerFunc) *MockImiddlewares_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTokenAnd_ADMIN provides a mock function with given fields: next
func (_m *MockImiddlewares) ValidateTokenAnd_ADMIN(next echo.HandlerFunc) echo.HandlerFunc {
	ret := _m.Called(next)

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func(echo.HandlerFunc) echo.HandlerFunc); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// MockImiddlewares_ValidateTokenAnd_ADMIN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTokenAnd_ADMIN'
type MockImiddlewares_ValidateTokenAnd_ADMIN_Call struct {
	*mock.Call
}

// ValidateTokenAnd_ADMIN is a helper method to define mock.On call
//   - next echo.HandlerFunc
func (_e *MockImiddlewares_Expecter) ValidateTokenAnd_ADMIN(next interface{}) *MockImiddlewares_ValidateTokenAnd_ADMIN_Call {
	return &MockImiddlewares_ValidateTokenAnd_ADMIN_Call{Call: _e.mock.On("ValidateTokenAnd_ADMIN", next)}
}

func (_c *MockImiddlewares_ValidateTokenAnd_ADMIN_Call) Run(run func(next echo.HandlerFunc)) *MockImiddlewares_ValidateTokenAnd_ADMIN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.HandlerFunc))
	})
	return _c
}

func (_c *MockImiddlewares_ValidateTokenAnd_ADMIN_Call) Return(_a0 echo.HandlerFunc) *MockImiddlewares_ValidateTokenAnd_ADMIN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImiddlewares_ValidateTokenAnd_ADMIN_Call) RunAndReturn(run func(echo.HandlerFunc) echo.HandlerFunc) *MockImiddlewares_ValidateTokenAnd_ADMIN_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImiddlewares creates a new instance of MockImiddlewares. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImiddlewares(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImiddlewares {
	mock := &MockImiddlewares{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
