basePath: /api/v1
definitions:
  requestDto.RegisterUserDto:
    properties:
      confirmation:
        type: string
      email:
        type: string
      name:
        minLength: 3
        type: string
      password:
        minLength: 3
        type: string
    required:
    - confirmation
    - email
    - name
    - password
    type: object
  responseDto.ResponseDto:
    properties:
      data: {}
      message:
        type: string
      messageType:
        type: string
    type: object
  responseDto.UserDto:
    properties:
      email:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  swaggertypes.SwaggerCustomTypes:
    type: object
info:
  contact: {}
  title: StudyNotes API docTemplate
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Charge new user into the database
      parameters:
      - description: request body
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/requestDto.RegisterUserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responseDto.ResponseDto'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/swaggertypes.SwaggerCustomTypes'
                  - properties:
                      token:
                        type: string
                      user:
                        $ref: '#/definitions/responseDto.UserDto'
                    type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/responseDto.ResponseDto'
            - properties:
                data:
                  type: object
              type: object
      summary: Register new user
      tags:
      - Auth
  /user/all:
    get:
      consumes:
      - application/json
      description: List all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responseDto.ResponseDto'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/responseDto.UserDto'
                  type: array
              type: object
      summary: List all users
      tags:
      - User
swagger: "2.0"
