name: Deploy pipeline

on:
  push:
    branches: [master, develop]
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql database: 'studyNotes' # Optional, default value is "test". The specified database which will be create
          mysql root password: '123luciano456' # Required if "mysql user" is empty, default is empty. The root superuser password

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Install dependencies
        run: go mod download

      - name: run
        run: go build .

      - name: Test
        run: go test -v ./...

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
